name: Map and Deploy JSON to Cal.com

on:
  push:
    branches:
      - main
    paths:
      - 'packages.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Verify packages.json
        run: |
          if [ ! -f packages.json ]; then
            echo "Error: packages.json not found"
            exit 1
          fi

      - name: Write event type script
        run: |
          cat <<'SCRIPT' > deploy.js
          const fs = require('fs');
          const https = require('https');
          const dayMap = {
            'Monday': 'Monday', 'Tuesday': 'Tuesday', 'Wednesday': 'Wednesday', 'Thursday': 'Thursday',
            'Friday': 'Friday', 'Saturday': 'Saturday', 'Sunday': 'Sunday',
            1: 'Monday', 2: 'Tuesday', 3: 'Wednesday', 4: 'Thursday', 5: 'Friday', 6: 'Saturday', 7: 'Sunday'
          };
          function apiRequest(method, path, body = null) {
            return new Promise((resolve, reject) => {
              const options = {
                hostname: 'api.cal.com',
                path: path,
                method: method,
                headers: {
                  'Authorization': 'Bearer ' + process.env.CALCOM_API_KEY,
                  'Content-Type': 'application/json',
                  'cal-api-version': '2024-06-14'
                }
              };
              const req = https.request(options, (res) => {
                let data = '';
                res.on('data', (chunk) => { data += chunk; });
                res.on('end', () => {
                  if (res.statusCode >= 200 && res.statusCode < 300) {
                    try {
                      resolve(JSON.parse(data));
                    } catch (e) {
                      reject(e);
                    }
                  } else {
                    reject({ statusCode: res.statusCode, data: data });
                  }
                });
              });
              req.on('error', (e) => { reject(e); });
              if (body) req.write(JSON.stringify(body));
              req.end();
            });
          }
          async function getEventTypeId(slug) {
            try {
              const res = await apiRequest('GET', '/v2/event-types?slug=' + encodeURIComponent(slug));
              const eventTypes = res.event_types || [];
              return eventTypes.length > 0 ? eventTypes[0].id : null;
            } catch (e) {
              return null;
            }
          }
          async function getEventType(id) {
            try {
              const res = await apiRequest('GET', '/v2/event-types/' + id);
              return res.data;
            } catch (e) {
              return null;
            }
          }
          async function deleteEventType(id) {
            try {
              await apiRequest('DELETE', '/v2/event-types/' + id);
            } catch (e) {}
          }
          async function createSchedule(scheduleData) {
            try {
              const mappedAvailability = scheduleData.availability.map(slot => ({
                ...slot,
                days: slot.days.map(day => dayMap[day] || day)
              }));
              const payload = {
                name: scheduleData.name,
                timeZone: scheduleData.timeZone || "America/Toronto",
                isDefault: scheduleData.isDefault !== undefined ? scheduleData.isDefault : true,
                availability: mappedAvailability
              };
              const result = await apiRequest('POST', '/v2/schedules', payload);
              return result.data.id;
            } catch (e) {
              throw new Error('Failed to create schedule: ' + JSON.stringify(e));
            }
          }
          async function verifyEventType(slug, expected, eventTypeId) {
            const eventType = await getEventType(eventTypeId);
            if (!eventType || eventType.slug !== slug) {
              throw new Error('Event type not found for slug: ' + slug);
            }
            const errors = [];
            if (expected.bookingFields) {
              const hasEventAddress = eventType.bookingFields.some(field => 
                field.slug === 'eventAddress' && 
                field.type === 'textarea' && 
                field.required === true &&
                field.label === 'Event Address'
              );
              if (!hasEventAddress) {
                errors.push('bookingFields: missing eventAddress field');
              }
            }
            if (errors.length > 0) {
              throw new Error('Verification failed for ' + slug + ': ' + errors.join('; '));
            }
          }
          async function processEvents() {
            try {
              let packages = JSON.parse(fs.readFileSync('packages.json'));
              if (packages.some(pkg => Object.keys(pkg).length === 1)) {
                packages = packages.map(pkg => Object.values(pkg)[0]);
              }
              for (const pkg of packages) {
                if (!pkg.slug || !pkg.name) {
                  throw new Error('Invalid package: missing slug or name');
                }
                const priceText = pkg.discount > 0 
                  ? `**Price**: **$${pkg.price}** (Reg. ~~$${pkg.regularPrice}~~) - ${pkg.discount}% OFF!`
                  : `**Price**: **$${pkg.price}**`;
                const servicesText = pkg.servicesIncluded && Array.isArray(pkg.servicesIncluded)
                  ? `**Services Included**:\n${pkg.servicesIncluded.map(s => `- ${s}`).join('\n')}`
                  : `**Services Included**: None`;
                const description = [
                  priceText,
                  `**Description**: ${pkg.description || 'No description provided'}`,
                  `**Guests**: ${pkg.guests || 'Not specified'}`,
                  `**Duration**: Up to ${pkg.maxDuration || 3} hours`,
                  servicesText,
                  `**Note**: ${pkg.note || 'No additional notes'}`
                ].join('\n\n');
                const transformed = {
                  title: pkg.name,
                  slug: pkg.slug,
                  lengthInMinutes: pkg.maxDuration ? pkg.maxDuration * 60 : 180,
                  description: description,
                  locations: pkg.locations && Array.isArray(pkg.locations) && pkg.locations[0]?.location_type === 'ask'
                    ? [{ type: 'address', address: 'To be provided by client', public: true }]
                    : [{ type: 'address', address: pkg.location || 'Toronto, ON', public: true }],
                  availability: pkg.availability || {
                    days: pkg.availabilityDays || ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
                    startTime: pkg.startTime || '09:00',
                    endTime: pkg.endTime || '23:59'
                  },
                  tags: [],
                  disableGuests: pkg.disableGuests || false,
                  metadata: {
                    disableCalVideoTranscription: pkg.disableCalVideoTranscription || false,
                    disableGuestsCancelling: pkg.disableGuestsCancelling || false,
                    disableGuestsRescheduling: pkg.disableGuestsRescheduling || false
                  },
                  bookingFields: pkg.bookingFields || [],
                  color: pkg.color || undefined,
                  minimumBookingNotice: pkg.minimumBookingNotice || undefined,
                  bookerLayouts: pkg.bookerLayouts || undefined
                };
                if (Array.isArray(pkg.eventType)) {
                  transformed.tags = transformed.tags.concat(pkg.eventType);
                }
                if (pkg.packageType) transformed.tags.push(pkg.packageType);
                if (pkg.Sale === 'Y') transformed.tags.push('On Sale');
                if (pkg.New === 'Y') transformed.tags.push('New');
                if (pkg.availability && Array.isArray(pkg.availability.schedules)) {
                  const scheduleIds = [];
                  for (const schedule of pkg.availability.schedules) {
                    const scheduleId = await createSchedule(schedule);
                    scheduleIds.push(scheduleId);
                  }
                  if (scheduleIds.length > 0) {
                    transformed.scheduleIds = scheduleIds;
                  }
                }
                const existingEventTypeId = await getEventTypeId(transformed.slug);
                if (existingEventTypeId) {
                  await deleteEventType(existingEventTypeId);
                }
                const result = await apiRequest('POST', '/v2/event-types', transformed);
                await verifyEventType(pkg.slug, transformed, result.data.id);
                await new Promise(resolve => setTimeout(resolve, 5000));
              }
            } catch (e) {
              console.error('Error: ' + (e.message || JSON.stringify(e)));
              process.exit(1);
            }
          }
          processEvents();
          SCRIPT

      - name: Create event types
        env:
          CALCOM_API_KEY: ${{ secrets.CALCOM_API_KEY }}
        run: node deploy.js

      - name: Write payment configuration script
        run: |
          cat <<'SCRIPT' > configure-payments.js
          const fs = require('fs');
          const https = require('https');
          function apiRequest(method, path, body = null) {
            return new Promise((resolve, reject) => {
              const options = {
                hostname: 'api.cal.com',
                path: path,
                method: method,
                headers: {
                  'Authorization': 'Bearer ' + process.env.CALCOM_API_KEY,
                  'Content-Type': 'application/json',
                  'cal-api-version': '2024-06-14'
                }
              };
              const req = https.request(options, (res) => {
                let data = '';
                res.on('data', (chunk) => { data += chunk; });
                res.on('end', () => {
                  if (res.statusCode >= 200 && res.statusCode < 300) {
                    try {
                      resolve(JSON.parse(data));
                    } catch (e) {
                      reject(e);
                    }
                  } else {
                    reject({ statusCode: res.statusCode, data: data });
                  }
                });
              });
              req.on('error', (e) => { reject(e); });
              if (body) req.write(JSON.stringify(body));
              req.end();
            });
          }
          async function getEventTypeId(slug) {
            try {
              const res = await apiRequest('GET', '/v2/event-types?slug=' + encodeURIComponent(slug));
              const eventTypes = res.event_types || [];
              return eventTypes.length > 0 ? eventTypes[0].id : null;
            } catch (e) {
              return null;
            }
          }
          async function configurePayments() {
            try {
              let packages = JSON.parse(fs.readFileSync('packages.json'));
              if (packages.some(pkg => Object.keys(pkg).length === 1)) {
                packages = packages.map(pkg => Object.values(pkg)[0]);
              }
              for (const pkg of packages) {
                if (!pkg.slug || !pkg.name) {
                  throw new Error('Invalid package: missing slug or name');
                }
                if (!pkg.price || pkg.price <= 0) {
                  continue;
                }
                const eventTypeId = await getEventTypeId(pkg.slug);
                if (!eventTypeId) {
                  continue;
                }
                const paymentPayload = {
                  price: Math.round(pkg.price * 100),
                  currency: pkg.currency?.toLowerCase() || 'cad',
                  metadata: {
                    apps: {
                      stripe: {
                        enabled: true,
                        price: Math.round(pkg.price * 100),
                        currency: pkg.currency?.toLowerCase() || 'cad'
                      }
                    }
                  }
                };
                await apiRequest('PATCH', '/v2/event-types/' + eventTypeId, paymentPayload);
                await new Promise(resolve => setTimeout(resolve, 2000));
              }
            } catch (e) {
              console.error('Error: ' + (e.message || JSON.stringify(e)));
              process.exit(1);
            }
          }
          configurePayments();
          SCRIPT

      - name: Configure payments
        env:
          CALCOM_API_KEY: ${{ secrets.CALCOM_API_KEY }}
        run: node configure-payments.js
